#
# Configuration
#

language: cpp

dist: trusty
sudo: required

#
# Compilers
#
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.8
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.8
      - clang-3.9
      - clang-tidy-3.8
      - clang-tidy-3.9
      - gcc-5
      - g++-5
      - nasm

#
# Update Build Environment
#
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
  - chmod +x cmake-3.7.2-Linux-x86_64.sh
  - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 100
  - sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-3.8 100
  - cd ..
  - git clone https://github.com/bareflank/hypervisor.git
  - mv extended_apis hypervisor/
  - cd hypervisor

#
# Build Matrix
#
matrix:
  include:

  #
  # Astyle
  #
  - os: linux
    env:
      - TEST="Astyle"
    script:
      - if [[ -n $(./tools/astyle/run.sh | grep Formatted) ]]; then echo "You must run astyle before submitting a pull request"; exit -1; fi

  #
  # Doxygen
  #
  - os: linux
    env:
      - TEST="Doxygen"
    script:
      - ./configure
      - make doxygen
      - if cat doc/doxygen_warnings.txt | grep FIX; then echo "You must fix doxygen before submitting a pull request"; exit -1; fi

  #
  # Git Check
  #
  - os: linux
    env:
      - TEST="Git Check"
    script:
      - if [[ -n $(git diff --check HEAD^) ]]; then echo "You must remove whitespace before submitting a pull request"; exit -1; fi

  #
  # Codecov
  #
  - os: linux
    env:
      - TEST="Codecov"
    script:
      - ./configure --compiler clang-3.8
      - CC=clang-3.8 CXX=clang++-3.8 COVERALLS=true make
      - make test
    after_success:
      - cd extended_apis
      - ./tools/codecov/codecov.sh -s . -p ../makefiles/extended_apis/ -c -x ./tools/codecov/llvm-gcov.sh

  #
  # Clang Tidy
  #
  - os: linux
    env:
      - TEST="Clang Tidy"
    install:
      - git clone https://github.com/rizsotto/bear.git
      - pushd bear; cmake .; make; sudo make install; popd
    script:
      - ./configure --compiler clang-3.8
      - STATIC_ANALYSIS_ENABLED=true bear make
      - HYPERKERNEL_EXTENSION=true make tidy

  #
  # Google Sanitizers
  #
  - os: linux
    env:
      - TEST="Google Sanitizers"
    script:
      - ./configure --compiler clang-3.8
      - DYNAMIC_ANALYSIS_ENABLED=true make
      - make test

  #
  # Clang 3.8
  #
  - os: linux
    env:
      - TEST="Clang 3.8"
    script:
      - ./configure --compiler clang-3.8
      - make
      - make test

  #
  # Clang 3.9
  #
  - os: linux
    env:
      - TEST="Clang 3.9"
    script:
      - ./configure --compiler clang-3.9
      - make
      - make test
