//
// Bareflank Hypervisor
//
// Copyright (C) 2015 Assured Information Security, Inc.
// Author: Rian Quinn        <quinnr@ainfosec.com>
// Author: Brendan Kerrigan  <kerriganb@ainfosec.com>
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#include <bftypes.h>
#include <bfexports.h>

extern "C" void EXPORT_SYM _isr0(void) noexcept {}
extern "C" void EXPORT_SYM _isr1(void) noexcept {}
extern "C" void EXPORT_SYM _isr2(void) noexcept {}
extern "C" void EXPORT_SYM _isr3(void) noexcept {}
extern "C" void EXPORT_SYM _isr4(void) noexcept {}
extern "C" void EXPORT_SYM _isr5(void) noexcept {}
extern "C" void EXPORT_SYM _isr6(void) noexcept {}
extern "C" void EXPORT_SYM _isr7(void) noexcept {}
extern "C" void EXPORT_SYM _isr8(void) noexcept {}
extern "C" void EXPORT_SYM _isr9(void) noexcept {}
extern "C" void EXPORT_SYM _isr10(void) noexcept {}
extern "C" void EXPORT_SYM _isr11(void) noexcept {}
extern "C" void EXPORT_SYM _isr12(void) noexcept {}
extern "C" void EXPORT_SYM _isr13(void) noexcept {}
extern "C" void EXPORT_SYM _isr14(void) noexcept {}
extern "C" void EXPORT_SYM _isr15(void) noexcept {}
extern "C" void EXPORT_SYM _isr16(void) noexcept {}
extern "C" void EXPORT_SYM _isr17(void) noexcept {}
extern "C" void EXPORT_SYM _isr18(void) noexcept {}
extern "C" void EXPORT_SYM _isr19(void) noexcept {}
extern "C" void EXPORT_SYM _isr20(void) noexcept {}
extern "C" void EXPORT_SYM _isr21(void) noexcept {}
extern "C" void EXPORT_SYM _isr22(void) noexcept {}
extern "C" void EXPORT_SYM _isr23(void) noexcept {}
extern "C" void EXPORT_SYM _isr24(void) noexcept {}
extern "C" void EXPORT_SYM _isr25(void) noexcept {}
extern "C" void EXPORT_SYM _isr26(void) noexcept {}
extern "C" void EXPORT_SYM _isr27(void) noexcept {}
extern "C" void EXPORT_SYM _isr28(void) noexcept {}
extern "C" void EXPORT_SYM _isr29(void) noexcept {}
extern "C" void EXPORT_SYM _isr30(void) noexcept {}
extern "C" void EXPORT_SYM _isr31(void) noexcept {}
extern "C" void EXPORT_SYM _isr32(void) noexcept {}
extern "C" void EXPORT_SYM _isr33(void) noexcept {}
extern "C" void EXPORT_SYM _isr34(void) noexcept {}
extern "C" void EXPORT_SYM _isr35(void) noexcept {}
extern "C" void EXPORT_SYM _isr36(void) noexcept {}
extern "C" void EXPORT_SYM _isr37(void) noexcept {}
extern "C" void EXPORT_SYM _isr38(void) noexcept {}
extern "C" void EXPORT_SYM _isr39(void) noexcept {}
extern "C" void EXPORT_SYM _isr40(void) noexcept {}
extern "C" void EXPORT_SYM _isr41(void) noexcept {}
extern "C" void EXPORT_SYM _isr42(void) noexcept {}
extern "C" void EXPORT_SYM _isr43(void) noexcept {}
extern "C" void EXPORT_SYM _isr44(void) noexcept {}
extern "C" void EXPORT_SYM _isr45(void) noexcept {}
extern "C" void EXPORT_SYM _isr46(void) noexcept {}
extern "C" void EXPORT_SYM _isr47(void) noexcept {}
extern "C" void EXPORT_SYM _isr48(void) noexcept {}
extern "C" void EXPORT_SYM _isr49(void) noexcept {}
extern "C" void EXPORT_SYM _isr50(void) noexcept {}
extern "C" void EXPORT_SYM _isr51(void) noexcept {}
extern "C" void EXPORT_SYM _isr52(void) noexcept {}
extern "C" void EXPORT_SYM _isr53(void) noexcept {}
extern "C" void EXPORT_SYM _isr54(void) noexcept {}
extern "C" void EXPORT_SYM _isr55(void) noexcept {}
extern "C" void EXPORT_SYM _isr56(void) noexcept {}
extern "C" void EXPORT_SYM _isr57(void) noexcept {}
extern "C" void EXPORT_SYM _isr58(void) noexcept {}
extern "C" void EXPORT_SYM _isr59(void) noexcept {}
extern "C" void EXPORT_SYM _isr60(void) noexcept {}
extern "C" void EXPORT_SYM _isr61(void) noexcept {}
extern "C" void EXPORT_SYM _isr62(void) noexcept {}
extern "C" void EXPORT_SYM _isr63(void) noexcept {}
extern "C" void EXPORT_SYM _isr64(void) noexcept {}
extern "C" void EXPORT_SYM _isr65(void) noexcept {}
extern "C" void EXPORT_SYM _isr66(void) noexcept {}
extern "C" void EXPORT_SYM _isr67(void) noexcept {}
extern "C" void EXPORT_SYM _isr68(void) noexcept {}
extern "C" void EXPORT_SYM _isr69(void) noexcept {}
extern "C" void EXPORT_SYM _isr70(void) noexcept {}
extern "C" void EXPORT_SYM _isr71(void) noexcept {}
extern "C" void EXPORT_SYM _isr72(void) noexcept {}
extern "C" void EXPORT_SYM _isr73(void) noexcept {}
extern "C" void EXPORT_SYM _isr74(void) noexcept {}
extern "C" void EXPORT_SYM _isr75(void) noexcept {}
extern "C" void EXPORT_SYM _isr76(void) noexcept {}
extern "C" void EXPORT_SYM _isr77(void) noexcept {}
extern "C" void EXPORT_SYM _isr78(void) noexcept {}
extern "C" void EXPORT_SYM _isr79(void) noexcept {}
extern "C" void EXPORT_SYM _isr80(void) noexcept {}
extern "C" void EXPORT_SYM _isr81(void) noexcept {}
extern "C" void EXPORT_SYM _isr82(void) noexcept {}
extern "C" void EXPORT_SYM _isr83(void) noexcept {}
extern "C" void EXPORT_SYM _isr84(void) noexcept {}
extern "C" void EXPORT_SYM _isr85(void) noexcept {}
extern "C" void EXPORT_SYM _isr86(void) noexcept {}
extern "C" void EXPORT_SYM _isr87(void) noexcept {}
extern "C" void EXPORT_SYM _isr88(void) noexcept {}
extern "C" void EXPORT_SYM _isr89(void) noexcept {}
extern "C" void EXPORT_SYM _isr90(void) noexcept {}
extern "C" void EXPORT_SYM _isr91(void) noexcept {}
extern "C" void EXPORT_SYM _isr92(void) noexcept {}
extern "C" void EXPORT_SYM _isr93(void) noexcept {}
extern "C" void EXPORT_SYM _isr94(void) noexcept {}
extern "C" void EXPORT_SYM _isr95(void) noexcept {}
extern "C" void EXPORT_SYM _isr96(void) noexcept {}
extern "C" void EXPORT_SYM _isr97(void) noexcept {}
extern "C" void EXPORT_SYM _isr98(void) noexcept {}
extern "C" void EXPORT_SYM _isr99(void) noexcept {}
extern "C" void EXPORT_SYM _isr100(void) noexcept {}
extern "C" void EXPORT_SYM _isr101(void) noexcept {}
extern "C" void EXPORT_SYM _isr102(void) noexcept {}
extern "C" void EXPORT_SYM _isr103(void) noexcept {}
extern "C" void EXPORT_SYM _isr104(void) noexcept {}
extern "C" void EXPORT_SYM _isr105(void) noexcept {}
extern "C" void EXPORT_SYM _isr106(void) noexcept {}
extern "C" void EXPORT_SYM _isr107(void) noexcept {}
extern "C" void EXPORT_SYM _isr108(void) noexcept {}
extern "C" void EXPORT_SYM _isr109(void) noexcept {}
extern "C" void EXPORT_SYM _isr110(void) noexcept {}
extern "C" void EXPORT_SYM _isr111(void) noexcept {}
extern "C" void EXPORT_SYM _isr112(void) noexcept {}
extern "C" void EXPORT_SYM _isr113(void) noexcept {}
extern "C" void EXPORT_SYM _isr114(void) noexcept {}
extern "C" void EXPORT_SYM _isr115(void) noexcept {}
extern "C" void EXPORT_SYM _isr116(void) noexcept {}
extern "C" void EXPORT_SYM _isr117(void) noexcept {}
extern "C" void EXPORT_SYM _isr118(void) noexcept {}
extern "C" void EXPORT_SYM _isr119(void) noexcept {}
extern "C" void EXPORT_SYM _isr120(void) noexcept {}
extern "C" void EXPORT_SYM _isr121(void) noexcept {}
extern "C" void EXPORT_SYM _isr122(void) noexcept {}
extern "C" void EXPORT_SYM _isr123(void) noexcept {}
extern "C" void EXPORT_SYM _isr124(void) noexcept {}
extern "C" void EXPORT_SYM _isr125(void) noexcept {}
extern "C" void EXPORT_SYM _isr126(void) noexcept {}
extern "C" void EXPORT_SYM _isr127(void) noexcept {}
extern "C" void EXPORT_SYM _isr128(void) noexcept {}
extern "C" void EXPORT_SYM _isr129(void) noexcept {}
extern "C" void EXPORT_SYM _isr130(void) noexcept {}
extern "C" void EXPORT_SYM _isr131(void) noexcept {}
extern "C" void EXPORT_SYM _isr132(void) noexcept {}
extern "C" void EXPORT_SYM _isr133(void) noexcept {}
extern "C" void EXPORT_SYM _isr134(void) noexcept {}
extern "C" void EXPORT_SYM _isr135(void) noexcept {}
extern "C" void EXPORT_SYM _isr136(void) noexcept {}
extern "C" void EXPORT_SYM _isr137(void) noexcept {}
extern "C" void EXPORT_SYM _isr138(void) noexcept {}
extern "C" void EXPORT_SYM _isr139(void) noexcept {}
extern "C" void EXPORT_SYM _isr140(void) noexcept {}
extern "C" void EXPORT_SYM _isr141(void) noexcept {}
extern "C" void EXPORT_SYM _isr142(void) noexcept {}
extern "C" void EXPORT_SYM _isr143(void) noexcept {}
extern "C" void EXPORT_SYM _isr144(void) noexcept {}
extern "C" void EXPORT_SYM _isr145(void) noexcept {}
extern "C" void EXPORT_SYM _isr146(void) noexcept {}
extern "C" void EXPORT_SYM _isr147(void) noexcept {}
extern "C" void EXPORT_SYM _isr148(void) noexcept {}
extern "C" void EXPORT_SYM _isr149(void) noexcept {}
extern "C" void EXPORT_SYM _isr150(void) noexcept {}
extern "C" void EXPORT_SYM _isr151(void) noexcept {}
extern "C" void EXPORT_SYM _isr152(void) noexcept {}
extern "C" void EXPORT_SYM _isr153(void) noexcept {}
extern "C" void EXPORT_SYM _isr154(void) noexcept {}
extern "C" void EXPORT_SYM _isr155(void) noexcept {}
extern "C" void EXPORT_SYM _isr156(void) noexcept {}
extern "C" void EXPORT_SYM _isr157(void) noexcept {}
extern "C" void EXPORT_SYM _isr158(void) noexcept {}
extern "C" void EXPORT_SYM _isr159(void) noexcept {}
extern "C" void EXPORT_SYM _isr160(void) noexcept {}
extern "C" void EXPORT_SYM _isr161(void) noexcept {}
extern "C" void EXPORT_SYM _isr162(void) noexcept {}
extern "C" void EXPORT_SYM _isr163(void) noexcept {}
extern "C" void EXPORT_SYM _isr164(void) noexcept {}
extern "C" void EXPORT_SYM _isr165(void) noexcept {}
extern "C" void EXPORT_SYM _isr166(void) noexcept {}
extern "C" void EXPORT_SYM _isr167(void) noexcept {}
extern "C" void EXPORT_SYM _isr168(void) noexcept {}
extern "C" void EXPORT_SYM _isr169(void) noexcept {}
extern "C" void EXPORT_SYM _isr170(void) noexcept {}
extern "C" void EXPORT_SYM _isr171(void) noexcept {}
extern "C" void EXPORT_SYM _isr172(void) noexcept {}
extern "C" void EXPORT_SYM _isr173(void) noexcept {}
extern "C" void EXPORT_SYM _isr174(void) noexcept {}
extern "C" void EXPORT_SYM _isr175(void) noexcept {}
extern "C" void EXPORT_SYM _isr176(void) noexcept {}
extern "C" void EXPORT_SYM _isr177(void) noexcept {}
extern "C" void EXPORT_SYM _isr178(void) noexcept {}
extern "C" void EXPORT_SYM _isr179(void) noexcept {}
extern "C" void EXPORT_SYM _isr180(void) noexcept {}
extern "C" void EXPORT_SYM _isr181(void) noexcept {}
extern "C" void EXPORT_SYM _isr182(void) noexcept {}
extern "C" void EXPORT_SYM _isr183(void) noexcept {}
extern "C" void EXPORT_SYM _isr184(void) noexcept {}
extern "C" void EXPORT_SYM _isr185(void) noexcept {}
extern "C" void EXPORT_SYM _isr186(void) noexcept {}
extern "C" void EXPORT_SYM _isr187(void) noexcept {}
extern "C" void EXPORT_SYM _isr188(void) noexcept {}
extern "C" void EXPORT_SYM _isr189(void) noexcept {}
extern "C" void EXPORT_SYM _isr190(void) noexcept {}
extern "C" void EXPORT_SYM _isr191(void) noexcept {}
extern "C" void EXPORT_SYM _isr192(void) noexcept {}
extern "C" void EXPORT_SYM _isr193(void) noexcept {}
extern "C" void EXPORT_SYM _isr194(void) noexcept {}
extern "C" void EXPORT_SYM _isr195(void) noexcept {}
extern "C" void EXPORT_SYM _isr196(void) noexcept {}
extern "C" void EXPORT_SYM _isr197(void) noexcept {}
extern "C" void EXPORT_SYM _isr198(void) noexcept {}
extern "C" void EXPORT_SYM _isr199(void) noexcept {}
extern "C" void EXPORT_SYM _isr200(void) noexcept {}
extern "C" void EXPORT_SYM _isr201(void) noexcept {}
extern "C" void EXPORT_SYM _isr202(void) noexcept {}
extern "C" void EXPORT_SYM _isr203(void) noexcept {}
extern "C" void EXPORT_SYM _isr204(void) noexcept {}
extern "C" void EXPORT_SYM _isr205(void) noexcept {}
extern "C" void EXPORT_SYM _isr206(void) noexcept {}
extern "C" void EXPORT_SYM _isr207(void) noexcept {}
extern "C" void EXPORT_SYM _isr208(void) noexcept {}
extern "C" void EXPORT_SYM _isr209(void) noexcept {}
extern "C" void EXPORT_SYM _isr210(void) noexcept {}
extern "C" void EXPORT_SYM _isr211(void) noexcept {}
extern "C" void EXPORT_SYM _isr212(void) noexcept {}
extern "C" void EXPORT_SYM _isr213(void) noexcept {}
extern "C" void EXPORT_SYM _isr214(void) noexcept {}
extern "C" void EXPORT_SYM _isr215(void) noexcept {}
extern "C" void EXPORT_SYM _isr216(void) noexcept {}
extern "C" void EXPORT_SYM _isr217(void) noexcept {}
extern "C" void EXPORT_SYM _isr218(void) noexcept {}
extern "C" void EXPORT_SYM _isr219(void) noexcept {}
extern "C" void EXPORT_SYM _isr220(void) noexcept {}
extern "C" void EXPORT_SYM _isr221(void) noexcept {}
extern "C" void EXPORT_SYM _isr222(void) noexcept {}
extern "C" void EXPORT_SYM _isr223(void) noexcept {}
extern "C" void EXPORT_SYM _isr224(void) noexcept {}
extern "C" void EXPORT_SYM _isr225(void) noexcept {}
extern "C" void EXPORT_SYM _isr226(void) noexcept {}
extern "C" void EXPORT_SYM _isr227(void) noexcept {}
extern "C" void EXPORT_SYM _isr228(void) noexcept {}
extern "C" void EXPORT_SYM _isr229(void) noexcept {}
extern "C" void EXPORT_SYM _isr230(void) noexcept {}
extern "C" void EXPORT_SYM _isr231(void) noexcept {}
extern "C" void EXPORT_SYM _isr232(void) noexcept {}
extern "C" void EXPORT_SYM _isr233(void) noexcept {}
extern "C" void EXPORT_SYM _isr234(void) noexcept {}
extern "C" void EXPORT_SYM _isr235(void) noexcept {}
extern "C" void EXPORT_SYM _isr236(void) noexcept {}
extern "C" void EXPORT_SYM _isr237(void) noexcept {}
extern "C" void EXPORT_SYM _isr238(void) noexcept {}
extern "C" void EXPORT_SYM _isr239(void) noexcept {}
extern "C" void EXPORT_SYM _isr240(void) noexcept {}
extern "C" void EXPORT_SYM _isr241(void) noexcept {}
extern "C" void EXPORT_SYM _isr242(void) noexcept {}
extern "C" void EXPORT_SYM _isr243(void) noexcept {}
extern "C" void EXPORT_SYM _isr244(void) noexcept {}
extern "C" void EXPORT_SYM _isr245(void) noexcept {}
extern "C" void EXPORT_SYM _isr246(void) noexcept {}
extern "C" void EXPORT_SYM _isr247(void) noexcept {}
extern "C" void EXPORT_SYM _isr248(void) noexcept {}
extern "C" void EXPORT_SYM _isr249(void) noexcept {}
extern "C" void EXPORT_SYM _isr250(void) noexcept {}
extern "C" void EXPORT_SYM _isr251(void) noexcept {}
extern "C" void EXPORT_SYM _isr252(void) noexcept {}
extern "C" void EXPORT_SYM _isr253(void) noexcept {}
extern "C" void EXPORT_SYM _isr254(void) noexcept {}
extern "C" void EXPORT_SYM _isr255(void) noexcept {}
